// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ScoresClient is the client API for Scores service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScoresClient interface {
	UpdateScores(ctx context.Context, in *UpdateScoresRequest, opts ...grpc.CallOption) (*UpdateScoresReply, error)
	GetScores(ctx context.Context, in *GetScoresRequest, opts ...grpc.CallOption) (*GetScoresReply, error)
}

type scoresClient struct {
	cc grpc.ClientConnInterface
}

func NewScoresClient(cc grpc.ClientConnInterface) ScoresClient {
	return &scoresClient{cc}
}

func (c *scoresClient) UpdateScores(ctx context.Context, in *UpdateScoresRequest, opts ...grpc.CallOption) (*UpdateScoresReply, error) {
	out := new(UpdateScoresReply)
	err := c.cc.Invoke(ctx, "/api.scores.v1.Scores/UpdateScores", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scoresClient) GetScores(ctx context.Context, in *GetScoresRequest, opts ...grpc.CallOption) (*GetScoresReply, error) {
	out := new(GetScoresReply)
	err := c.cc.Invoke(ctx, "/api.scores.v1.Scores/GetScores", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScoresServer is the server API for Scores service.
// All implementations must embed UnimplementedScoresServer
// for forward compatibility
type ScoresServer interface {
	UpdateScores(context.Context, *UpdateScoresRequest) (*UpdateScoresReply, error)
	GetScores(context.Context, *GetScoresRequest) (*GetScoresReply, error)
	mustEmbedUnimplementedScoresServer()
}

// UnimplementedScoresServer must be embedded to have forward compatible implementations.
type UnimplementedScoresServer struct {
}

func (UnimplementedScoresServer) UpdateScores(context.Context, *UpdateScoresRequest) (*UpdateScoresReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateScores not implemented")
}
func (UnimplementedScoresServer) GetScores(context.Context, *GetScoresRequest) (*GetScoresReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetScores not implemented")
}
func (UnimplementedScoresServer) mustEmbedUnimplementedScoresServer() {}

// UnsafeScoresServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScoresServer will
// result in compilation errors.
type UnsafeScoresServer interface {
	mustEmbedUnimplementedScoresServer()
}

func RegisterScoresServer(s grpc.ServiceRegistrar, srv ScoresServer) {
	s.RegisterService(&Scores_ServiceDesc, srv)
}

func _Scores_UpdateScores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateScoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoresServer).UpdateScores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.scores.v1.Scores/UpdateScores",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoresServer).UpdateScores(ctx, req.(*UpdateScoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scores_GetScores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoresServer).GetScores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.scores.v1.Scores/GetScores",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoresServer).GetScores(ctx, req.(*GetScoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Scores_ServiceDesc is the grpc.ServiceDesc for Scores service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Scores_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.scores.v1.Scores",
	HandlerType: (*ScoresServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateScores",
			Handler:    _Scores_UpdateScores_Handler,
		},
		{
			MethodName: "GetScores",
			Handler:    _Scores_GetScores_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/scores/v1/scores.proto",
}
