// Code generated by protoc-gen-go-http. DO NOT EDIT.

package v1

import (
	context "context"
	http1 "github.com/go-kratos/kratos/v2/transport/http"
	http "net/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
// context./http.
const _ = http1.SupportPackageIsVersion1

type ScoresHTTPServer interface {
	GetScores(context.Context, *GetScoresRequest) (*GetScoresReply, error)

	UpdateScores(context.Context, *UpdateScoresRequest) (*UpdateScoresReply, error)
}

func RegisterScoresHTTPServer(s http1.ServiceRegistrar, srv ScoresHTTPServer) {
	s.RegisterService(&_HTTP_Scores_serviceDesc, srv)
}

func _HTTP_Scores_UpdateScores_0(srv interface{}, ctx context.Context, req *http.Request, dec func(interface{}) error) (interface{}, error) {
	var in UpdateScoresRequest

	if err := dec(&in); err != nil {
		return nil, err
	}

	out, err := srv.(ScoresServer).UpdateScores(ctx, &in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _HTTP_Scores_GetScores_0(srv interface{}, ctx context.Context, req *http.Request, dec func(interface{}) error) (interface{}, error) {
	var in GetScoresRequest

	if err := http1.BindForm(req, &in); err != nil {
		return nil, err
	}

	if err := http1.BindVars(req, &in); err != nil {
		return nil, err
	}

	out, err := srv.(ScoresServer).GetScores(ctx, &in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _HTTP_Scores_serviceDesc = http1.ServiceDesc{
	ServiceName: "api.scores.v1.Scores",
	Methods: []http1.MethodDesc{

		{
			Path:    "/v1/scores",
			Method:  "PUT",
			Handler: _HTTP_Scores_UpdateScores_0,
		},

		{
			Path:    "/v1/scores/{id}",
			Method:  "GET",
			Handler: _HTTP_Scores_GetScores_0,
		},
	},
	Metadata: "api/scores/v1/scores.proto",
}
