// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: api/scores/v1/scores.proto

package v1

import (
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type UpdateScoresRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`       // 用户id
	Score int32 `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"` // +2:增加2积分, -2:减少2积分
}

func (x *UpdateScoresRequest) Reset() {
	*x = UpdateScoresRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_scores_v1_scores_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateScoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScoresRequest) ProtoMessage() {}

func (x *UpdateScoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_scores_v1_scores_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScoresRequest.ProtoReflect.Descriptor instead.
func (*UpdateScoresRequest) Descriptor() ([]byte, []int) {
	return file_api_scores_v1_scores_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateScoresRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateScoresRequest) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type UpdateScoresReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateScoresReply) Reset() {
	*x = UpdateScoresReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_scores_v1_scores_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateScoresReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScoresReply) ProtoMessage() {}

func (x *UpdateScoresReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_scores_v1_scores_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScoresReply.ProtoReflect.Descriptor instead.
func (*UpdateScoresReply) Descriptor() ([]byte, []int) {
	return file_api_scores_v1_scores_proto_rawDescGZIP(), []int{1}
}

type GetScoresRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetScoresRequest) Reset() {
	*x = GetScoresRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_scores_v1_scores_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetScoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScoresRequest) ProtoMessage() {}

func (x *GetScoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_scores_v1_scores_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScoresRequest.ProtoReflect.Descriptor instead.
func (*GetScoresRequest) Descriptor() ([]byte, []int) {
	return file_api_scores_v1_scores_proto_rawDescGZIP(), []int{2}
}

func (x *GetScoresRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetScoresReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Score int32 `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"`
}

func (x *GetScoresReply) Reset() {
	*x = GetScoresReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_scores_v1_scores_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetScoresReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScoresReply) ProtoMessage() {}

func (x *GetScoresReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_scores_v1_scores_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScoresReply.ProtoReflect.Descriptor instead.
func (*GetScoresReply) Descriptor() ([]byte, []int) {
	return file_api_scores_v1_scores_proto_rawDescGZIP(), []int{3}
}

func (x *GetScoresReply) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_api_scores_v1_scores_proto protoreflect.FileDescriptor

var file_api_scores_v1_scores_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x2f,
	0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x61, 0x70,
	0x69, 0x2e, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3b, 0x0a, 0x13, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x13, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x22, 0x0a, 0x10, 0x47,
	0x65, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x26, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x32, 0xdb, 0x01, 0x0a, 0x06, 0x53, 0x63, 0x6f, 0x72,
	0x65, 0x73, 0x12, 0x6b, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x63, 0x6f, 0x72,
	0x65, 0x73, 0x12, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x63, 0x6f,
	0x72, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x63, 0x6f,
	0x72, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f,
	0x1a, 0x0a, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x3a, 0x01, 0x2a, 0x12,
	0x64, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x12, 0x1f, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74,
	0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x17, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x11, 0x12, 0x0f, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73,
	0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x42, 0x2a, 0x0a, 0x0d, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x63, 0x6f,
	0x72, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x17, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x3b, 0x76,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_scores_v1_scores_proto_rawDescOnce sync.Once
	file_api_scores_v1_scores_proto_rawDescData = file_api_scores_v1_scores_proto_rawDesc
)

func file_api_scores_v1_scores_proto_rawDescGZIP() []byte {
	file_api_scores_v1_scores_proto_rawDescOnce.Do(func() {
		file_api_scores_v1_scores_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_scores_v1_scores_proto_rawDescData)
	})
	return file_api_scores_v1_scores_proto_rawDescData
}

var file_api_scores_v1_scores_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_scores_v1_scores_proto_goTypes = []interface{}{
	(*UpdateScoresRequest)(nil), // 0: api.scores.v1.UpdateScoresRequest
	(*UpdateScoresReply)(nil),   // 1: api.scores.v1.UpdateScoresReply
	(*GetScoresRequest)(nil),    // 2: api.scores.v1.GetScoresRequest
	(*GetScoresReply)(nil),      // 3: api.scores.v1.GetScoresReply
}
var file_api_scores_v1_scores_proto_depIdxs = []int32{
	0, // 0: api.scores.v1.Scores.UpdateScores:input_type -> api.scores.v1.UpdateScoresRequest
	2, // 1: api.scores.v1.Scores.GetScores:input_type -> api.scores.v1.GetScoresRequest
	1, // 2: api.scores.v1.Scores.UpdateScores:output_type -> api.scores.v1.UpdateScoresReply
	3, // 3: api.scores.v1.Scores.GetScores:output_type -> api.scores.v1.GetScoresReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_scores_v1_scores_proto_init() }
func file_api_scores_v1_scores_proto_init() {
	if File_api_scores_v1_scores_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_scores_v1_scores_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateScoresRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_scores_v1_scores_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateScoresReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_scores_v1_scores_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetScoresRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_scores_v1_scores_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetScoresReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_scores_v1_scores_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_scores_v1_scores_proto_goTypes,
		DependencyIndexes: file_api_scores_v1_scores_proto_depIdxs,
		MessageInfos:      file_api_scores_v1_scores_proto_msgTypes,
	}.Build()
	File_api_scores_v1_scores_proto = out.File
	file_api_scores_v1_scores_proto_rawDesc = nil
	file_api_scores_v1_scores_proto_goTypes = nil
	file_api_scores_v1_scores_proto_depIdxs = nil
}
