// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package errors

import (
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

const (
	Errors_PaperNoFound   = "Community_PaperNoFound"
	Errors_MusicExists    = "Community_MusicExists"
	Errors_MysqlErr       = "Community_MysqlErr"
	Errors_RedisErr       = "Community_RedisErr"
	Errors_FieldInvalid   = "Community_FieldInvalid"
	Errors_PageSizeNoZero = "Community_PageSizeNoZero"
)

func IsPaperNoFound(err error) bool {
	return errors.Reason(err) == Errors_PaperNoFound
}

func IsMusicExists(err error) bool {
	return errors.Reason(err) == Errors_MusicExists
}

func IsMysqlErr(err error) bool {
	return errors.Reason(err) == Errors_MysqlErr
}

func IsRedisErr(err error) bool {
	return errors.Reason(err) == Errors_RedisErr
}

func IsFieldInvalid(err error) bool {
	return errors.Reason(err) == Errors_FieldInvalid
}

func IsPageSizeNoZero(err error) bool {
	return errors.Reason(err) == Errors_PageSizeNoZero
}
