// Code generated by protoc-gen-go-http. DO NOT EDIT.

package v1

import (
	context "context"
	http1 "github.com/go-kratos/kratos/v2/transport/http"
	http "net/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
// context./http.
const _ = http1.SupportPackageIsVersion1

type CoinsHTTPServer interface {
	GetCoins(context.Context, *GetCoinsRequest) (*GetCoinsReply, error)

	UpdateCoins(context.Context, *UpdateCoinsRequest) (*UpdateCoinsReply, error)
}

func RegisterCoinsHTTPServer(s http1.ServiceRegistrar, srv CoinsHTTPServer) {
	s.RegisterService(&_HTTP_Coins_serviceDesc, srv)
}

func _HTTP_Coins_UpdateCoins_0(srv interface{}, ctx context.Context, req *http.Request, dec func(interface{}) error) (interface{}, error) {
	var in UpdateCoinsRequest

	if err := dec(&in); err != nil {
		return nil, err
	}

	out, err := srv.(CoinsServer).UpdateCoins(ctx, &in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _HTTP_Coins_GetCoins_0(srv interface{}, ctx context.Context, req *http.Request, dec func(interface{}) error) (interface{}, error) {
	var in GetCoinsRequest

	if err := http1.BindForm(req, &in); err != nil {
		return nil, err
	}

	if err := http1.BindVars(req, &in); err != nil {
		return nil, err
	}

	out, err := srv.(CoinsServer).GetCoins(ctx, &in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _HTTP_Coins_serviceDesc = http1.ServiceDesc{
	ServiceName: "api.coins.v1.Coins",
	Methods: []http1.MethodDesc{

		{
			Path:    "/v1/coins",
			Method:  "PUT",
			Handler: _HTTP_Coins_UpdateCoins_0,
		},

		{
			Path:    "/v1/coins/{id}",
			Method:  "GET",
			Handler: _HTTP_Coins_GetCoins_0,
		},
	},
	Metadata: "api/coins/v1/coins.proto",
}
