// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package errors

import (
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

const (
	Errors_NameExists       = "Community_NameExists"
	Errors_CommunityNoFound = "Community_CommunityNoFound"
	Errors_MysqlErr         = "Community_MysqlErr"
	Errors_FieldInvalid     = "Community_FieldInvalid"
)

func IsNameExists(err error) bool {
	return errors.Reason(err) == Errors_NameExists
}

func IsCommunityNoFound(err error) bool {
	return errors.Reason(err) == Errors_CommunityNoFound
}

func IsMysqlErr(err error) bool {
	return errors.Reason(err) == Errors_MysqlErr
}

func IsFieldInvalid(err error) bool {
	return errors.Reason(err) == Errors_FieldInvalid
}
