// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: api/paper/v1/paper.proto

package v1

import (
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CreatePaperRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OperatorId  int32  `protobuf:"varint,1,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`    // 创建者id
	CommunityId int32  `protobuf:"varint,2,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"` // 社区分类id
	Singer      string `protobuf:"bytes,3,opt,name=singer,proto3" json:"singer,omitempty"`                               // 歌手
	Song        string `protobuf:"bytes,4,opt,name=song,proto3" json:"song,omitempty"`                                   // 歌曲名
	Url         string `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`                                     // 资源链接
	Code        string `protobuf:"bytes,6,opt,name=code,proto3" json:"code,omitempty"`                                   // 资源密码
	Coin        int32  `protobuf:"varint,7,opt,name=coin,proto3" json:"coin,omitempty"`                                  // 收费硬币，0表示免费
}

func (x *CreatePaperRequest) Reset() {
	*x = CreatePaperRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_paper_v1_paper_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePaperRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaperRequest) ProtoMessage() {}

func (x *CreatePaperRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_paper_v1_paper_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaperRequest.ProtoReflect.Descriptor instead.
func (*CreatePaperRequest) Descriptor() ([]byte, []int) {
	return file_api_paper_v1_paper_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePaperRequest) GetOperatorId() int32 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *CreatePaperRequest) GetCommunityId() int32 {
	if x != nil {
		return x.CommunityId
	}
	return 0
}

func (x *CreatePaperRequest) GetSinger() string {
	if x != nil {
		return x.Singer
	}
	return ""
}

func (x *CreatePaperRequest) GetSong() string {
	if x != nil {
		return x.Song
	}
	return ""
}

func (x *CreatePaperRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreatePaperRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreatePaperRequest) GetCoin() int32 {
	if x != nil {
		return x.Coin
	}
	return 0
}

type CreatePaperReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreatePaperReply) Reset() {
	*x = CreatePaperReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_paper_v1_paper_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePaperReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaperReply) ProtoMessage() {}

func (x *CreatePaperReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_paper_v1_paper_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaperReply.ProtoReflect.Descriptor instead.
func (*CreatePaperReply) Descriptor() ([]byte, []int) {
	return file_api_paper_v1_paper_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePaperReply) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdatePaperRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                      // 文稿id
	CommunityId int32  `protobuf:"varint,2,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"` // 社区分类id
	State       int32  `protobuf:"varint,8,opt,name=state,proto3" json:"state,omitempty"`                                // 状态(0:审核, 1:正常, 2:异常待更新)
	Singer      string `protobuf:"bytes,3,opt,name=singer,proto3" json:"singer,omitempty"`                               // 歌手
	Song        string `protobuf:"bytes,4,opt,name=song,proto3" json:"song,omitempty"`                                   // 歌曲名
	Url         string `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`                                     // 资源链接
	Code        string `protobuf:"bytes,6,opt,name=code,proto3" json:"code,omitempty"`                                   // 资源密码
	Coin        int32  `protobuf:"varint,7,opt,name=coin,proto3" json:"coin,omitempty"`                                  // 收费硬币，0表示免费
	View        int32  `protobuf:"varint,9,opt,name=view,proto3" json:"view,omitempty"`                                  // 观看数
	Like        int32  `protobuf:"varint,10,opt,name=like,proto3" json:"like,omitempty"`                                 // 点赞数
	ReplyTime   int64  `protobuf:"varint,11,opt,name=reply_time,json=replyTime,proto3" json:"reply_time,omitempty"`      // 最后回复时间
	ReplyCount  int32  `protobuf:"varint,12,opt,name=reply_count,json=replyCount,proto3" json:"reply_count,omitempty"`   // 回复数
}

func (x *UpdatePaperRequest) Reset() {
	*x = UpdatePaperRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_paper_v1_paper_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePaperRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaperRequest) ProtoMessage() {}

func (x *UpdatePaperRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_paper_v1_paper_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaperRequest.ProtoReflect.Descriptor instead.
func (*UpdatePaperRequest) Descriptor() ([]byte, []int) {
	return file_api_paper_v1_paper_proto_rawDescGZIP(), []int{2}
}

func (x *UpdatePaperRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdatePaperRequest) GetCommunityId() int32 {
	if x != nil {
		return x.CommunityId
	}
	return 0
}

func (x *UpdatePaperRequest) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *UpdatePaperRequest) GetSinger() string {
	if x != nil {
		return x.Singer
	}
	return ""
}

func (x *UpdatePaperRequest) GetSong() string {
	if x != nil {
		return x.Song
	}
	return ""
}

func (x *UpdatePaperRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UpdatePaperRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpdatePaperRequest) GetCoin() int32 {
	if x != nil {
		return x.Coin
	}
	return 0
}

func (x *UpdatePaperRequest) GetView() int32 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *UpdatePaperRequest) GetLike() int32 {
	if x != nil {
		return x.Like
	}
	return 0
}

func (x *UpdatePaperRequest) GetReplyTime() int64 {
	if x != nil {
		return x.ReplyTime
	}
	return 0
}

func (x *UpdatePaperRequest) GetReplyCount() int32 {
	if x != nil {
		return x.ReplyCount
	}
	return 0
}

type UpdatePaperReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdatePaperReply) Reset() {
	*x = UpdatePaperReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_paper_v1_paper_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePaperReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaperReply) ProtoMessage() {}

func (x *UpdatePaperReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_paper_v1_paper_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaperReply.ProtoReflect.Descriptor instead.
func (*UpdatePaperReply) Descriptor() ([]byte, []int) {
	return file_api_paper_v1_paper_proto_rawDescGZIP(), []int{3}
}

type DeletePaperRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeletePaperRequest) Reset() {
	*x = DeletePaperRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_paper_v1_paper_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePaperRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePaperRequest) ProtoMessage() {}

func (x *DeletePaperRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_paper_v1_paper_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePaperRequest.ProtoReflect.Descriptor instead.
func (*DeletePaperRequest) Descriptor() ([]byte, []int) {
	return file_api_paper_v1_paper_proto_rawDescGZIP(), []int{4}
}

func (x *DeletePaperRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeletePaperReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeletePaperReply) Reset() {
	*x = DeletePaperReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_paper_v1_paper_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePaperReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePaperReply) ProtoMessage() {}

func (x *DeletePaperReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_paper_v1_paper_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePaperReply.ProtoReflect.Descriptor instead.
func (*DeletePaperReply) Descriptor() ([]byte, []int) {
	return file_api_paper_v1_paper_proto_rawDescGZIP(), []int{5}
}

type GetPaperRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetPaperRequest) Reset() {
	*x = GetPaperRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_paper_v1_paper_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPaperRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaperRequest) ProtoMessage() {}

func (x *GetPaperRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_paper_v1_paper_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaperRequest.ProtoReflect.Descriptor instead.
func (*GetPaperRequest) Descriptor() ([]byte, []int) {
	return file_api_paper_v1_paper_proto_rawDescGZIP(), []int{6}
}

func (x *GetPaperRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetPaperReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Paper *PaperStruct `protobuf:"bytes,1,opt,name=paper,proto3" json:"paper,omitempty"`
}

func (x *GetPaperReply) Reset() {
	*x = GetPaperReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_paper_v1_paper_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPaperReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaperReply) ProtoMessage() {}

func (x *GetPaperReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_paper_v1_paper_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaperReply.ProtoReflect.Descriptor instead.
func (*GetPaperReply) Descriptor() ([]byte, []int) {
	return file_api_paper_v1_paper_proto_rawDescGZIP(), []int{7}
}

func (x *GetPaperReply) GetPaper() *PaperStruct {
	if x != nil {
		return x.Paper
	}
	return nil
}

type GetPaperCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetPaperCodeRequest) Reset() {
	*x = GetPaperCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_paper_v1_paper_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPaperCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaperCodeRequest) ProtoMessage() {}

func (x *GetPaperCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_paper_v1_paper_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaperCodeRequest.ProtoReflect.Descriptor instead.
func (*GetPaperCodeRequest) Descriptor() ([]byte, []int) {
	return file_api_paper_v1_paper_proto_rawDescGZIP(), []int{8}
}

func (x *GetPaperCodeRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetPaperCodeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *GetPaperCodeReply) Reset() {
	*x = GetPaperCodeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_paper_v1_paper_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPaperCodeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaperCodeReply) ProtoMessage() {}

func (x *GetPaperCodeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_paper_v1_paper_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaperCodeReply.ProtoReflect.Descriptor instead.
func (*GetPaperCodeReply) Descriptor() ([]byte, []int) {
	return file_api_paper_v1_paper_proto_rawDescGZIP(), []int{9}
}

func (x *GetPaperCodeReply) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ListPaperRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommunityId int32 `protobuf:"varint,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"` // 社区id, 0表示全部
	PageNum     int32 `protobuf:"varint,2,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`             // 页码
	PageSize    int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`          // 页大小
}

func (x *ListPaperRequest) Reset() {
	*x = ListPaperRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_paper_v1_paper_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPaperRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaperRequest) ProtoMessage() {}

func (x *ListPaperRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_paper_v1_paper_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaperRequest.ProtoReflect.Descriptor instead.
func (*ListPaperRequest) Descriptor() ([]byte, []int) {
	return file_api_paper_v1_paper_proto_rawDescGZIP(), []int{10}
}

func (x *ListPaperRequest) GetCommunityId() int32 {
	if x != nil {
		return x.CommunityId
	}
	return 0
}

func (x *ListPaperRequest) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *ListPaperRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListPaperReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Papers []*PaperStruct `protobuf:"bytes,1,rep,name=papers,proto3" json:"papers,omitempty"`
}

func (x *ListPaperReply) Reset() {
	*x = ListPaperReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_paper_v1_paper_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPaperReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaperReply) ProtoMessage() {}

func (x *ListPaperReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_paper_v1_paper_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaperReply.ProtoReflect.Descriptor instead.
func (*ListPaperReply) Descriptor() ([]byte, []int) {
	return file_api_paper_v1_paper_proto_rawDescGZIP(), []int{11}
}

func (x *ListPaperReply) GetPapers() []*PaperStruct {
	if x != nil {
		return x.Papers
	}
	return nil
}

type PaperStruct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                      // 文稿id
	OwnerId     int32  `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`             // 所属主人
	CommunityId int32  `protobuf:"varint,3,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"` // 社区主题id
	State       int32  `protobuf:"varint,4,opt,name=state,proto3" json:"state,omitempty"`                                // 状态(0:审核, 1:正常, 2:异常待更新)
	ReplyCount  int32  `protobuf:"varint,5,opt,name=reply_count,json=replyCount,proto3" json:"reply_count,omitempty"`    // 回复数
	CreateTime  int64  `protobuf:"varint,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`    // 创建时间
	UpdateTime  int64  `protobuf:"varint,7,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`    // 最后更新时间
	ReplyTime   int64  `protobuf:"varint,8,opt,name=reply_time,json=replyTime,proto3" json:"reply_time,omitempty"`       // 最后回复时间
	Singer      string `protobuf:"bytes,9,opt,name=singer,proto3" json:"singer,omitempty"`                               // 歌手
	Song        string `protobuf:"bytes,10,opt,name=song,proto3" json:"song,omitempty"`                                  // 歌曲名
	Url         string `protobuf:"bytes,11,opt,name=url,proto3" json:"url,omitempty"`                                    // 资源地址
	View        int32  `protobuf:"varint,12,opt,name=view,proto3" json:"view,omitempty"`                                 // 访问量
	Like        int32  `protobuf:"varint,13,opt,name=like,proto3" json:"like,omitempty"`                                 // 点赞数
	Coin        int32  `protobuf:"varint,14,opt,name=coin,proto3" json:"coin,omitempty"`                                 // 所属硬币数
}

func (x *PaperStruct) Reset() {
	*x = PaperStruct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_paper_v1_paper_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaperStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaperStruct) ProtoMessage() {}

func (x *PaperStruct) ProtoReflect() protoreflect.Message {
	mi := &file_api_paper_v1_paper_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaperStruct.ProtoReflect.Descriptor instead.
func (*PaperStruct) Descriptor() ([]byte, []int) {
	return file_api_paper_v1_paper_proto_rawDescGZIP(), []int{12}
}

func (x *PaperStruct) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PaperStruct) GetOwnerId() int32 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *PaperStruct) GetCommunityId() int32 {
	if x != nil {
		return x.CommunityId
	}
	return 0
}

func (x *PaperStruct) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *PaperStruct) GetReplyCount() int32 {
	if x != nil {
		return x.ReplyCount
	}
	return 0
}

func (x *PaperStruct) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *PaperStruct) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *PaperStruct) GetReplyTime() int64 {
	if x != nil {
		return x.ReplyTime
	}
	return 0
}

func (x *PaperStruct) GetSinger() string {
	if x != nil {
		return x.Singer
	}
	return ""
}

func (x *PaperStruct) GetSong() string {
	if x != nil {
		return x.Song
	}
	return ""
}

func (x *PaperStruct) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PaperStruct) GetView() int32 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *PaperStruct) GetLike() int32 {
	if x != nil {
		return x.Like
	}
	return 0
}

func (x *PaperStruct) GetCoin() int32 {
	if x != nil {
		return x.Coin
	}
	return 0
}

var File_api_paper_v1_paper_proto protoreflect.FileDescriptor

var file_api_paper_v1_paper_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x61, 0x70, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x70,
	0x61, 0x70, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x61, 0x70, 0x69, 0x2e,
	0x70, 0x61, 0x70, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbe, 0x01, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x50, 0x61, 0x70, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a,
	0x0b, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x21,
	0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6f, 0x6e,
	0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6f, 0x6e, 0x67, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x69, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x63, 0x6f, 0x69, 0x6e, 0x22, 0x22, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x50, 0x61, 0x70, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0xab, 0x02, 0x0a, 0x12,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x70, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e,
	0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x69, 0x6e, 0x67, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x69, 0x6e,
	0x67, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6f, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x73, 0x6f, 0x6e, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x69, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x69,
	0x6e, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x69, 0x65, 0x77, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x76, 0x69, 0x65, 0x77, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6b, 0x65, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x6c, 0x69, 0x6b, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x70,
	0x6c, 0x79, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x72,
	0x65, 0x70, 0x6c, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x70, 0x6c,
	0x79, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x72,
	0x65, 0x70, 0x6c, 0x79, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x12, 0x0a, 0x10, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x50, 0x61, 0x70, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x24, 0x0a,
	0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x61, 0x70, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x12, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x61, 0x70,
	0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x21, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x50, 0x61,
	0x70, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x40, 0x0a, 0x0d, 0x47, 0x65,
	0x74, 0x50, 0x61, 0x70, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2f, 0x0a, 0x05, 0x70,
	0x61, 0x70, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x70, 0x61, 0x70, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x70, 0x65, 0x72, 0x53,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x05, 0x70, 0x61, 0x70, 0x65, 0x72, 0x22, 0x25, 0x0a, 0x13,
	0x47, 0x65, 0x74, 0x50, 0x61, 0x70, 0x65, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x27, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x50, 0x61, 0x70, 0x65, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x6d, 0x0a, 0x10,
	0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x70, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74,
	0x79, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x1b,
	0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x43, 0x0a, 0x0e, 0x4c,
	0x69, 0x73, 0x74, 0x50, 0x61, 0x70, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x31, 0x0a,
	0x06, 0x70, 0x61, 0x70, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x70, 0x61, 0x70, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x70,
	0x65, 0x72, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x06, 0x70, 0x61, 0x70, 0x65, 0x72, 0x73,
	0x22, 0xed, 0x02, 0x0a, 0x0b, 0x50, 0x61, 0x70, 0x65, 0x72, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x19, 0x0a, 0x08, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x63,
	0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x5f, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x72, 0x65, 0x70, 0x6c, 0x79,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x70, 0x6c, 0x79,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x72, 0x65, 0x70,
	0x6c, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x69, 0x6e, 0x67, 0x65, 0x72,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x6f, 0x6e, 0x67, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6f,
	0x6e, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x69, 0x65, 0x77, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x76, 0x69, 0x65, 0x77, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6b, 0x65,
	0x18, 0x0d, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6c, 0x69, 0x6b, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x69, 0x6e, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x69, 0x6e,
	0x32, 0xee, 0x04, 0x0a, 0x05, 0x50, 0x61, 0x70, 0x65, 0x72, 0x12, 0x65, 0x0a, 0x0b, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x70, 0x65, 0x72, 0x12, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x70, 0x61, 0x70, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50,
	0x61, 0x70, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x70, 0x61, 0x70, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x50, 0x61, 0x70, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x14, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x0e, 0x22, 0x09, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x61, 0x70, 0x65, 0x72, 0x3a, 0x01,
	0x2a, 0x12, 0x65, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x70, 0x65, 0x72,
	0x12, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x61, 0x70, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x70, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x61, 0x70, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x70, 0x65, 0x72, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x14, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0e, 0x1a, 0x09, 0x2f, 0x76, 0x31, 0x2f,
	0x70, 0x61, 0x70, 0x65, 0x72, 0x3a, 0x01, 0x2a, 0x12, 0x67, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x50, 0x61, 0x70, 0x65, 0x72, 0x12, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x61,
	0x70, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x61, 0x70,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x70, 0x61, 0x70, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50,
	0x61, 0x70, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x16, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x10, 0x2a, 0x0e, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x61, 0x70, 0x65, 0x72, 0x2f, 0x7b, 0x69, 0x64,
	0x7d, 0x12, 0x5e, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x50, 0x61, 0x70, 0x65, 0x72, 0x12, 0x1d, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x70, 0x61, 0x70, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74,
	0x50, 0x61, 0x70, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x70, 0x61, 0x70, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x50,
	0x61, 0x70, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x16, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x10, 0x12, 0x0e, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x61, 0x70, 0x65, 0x72, 0x2f, 0x7b, 0x69, 0x64,
	0x7d, 0x12, 0x6d, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x50, 0x61, 0x70, 0x65, 0x72, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x61, 0x70, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x70, 0x65, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x61, 0x70, 0x65, 0x72,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x70, 0x65, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x19, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x13, 0x12, 0x0e, 0x2f,
	0x76, 0x31, 0x2f, 0x70, 0x61, 0x70, 0x65, 0x72, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x3a, 0x01, 0x2a,
	0x12, 0x5f, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x70, 0x65, 0x72, 0x12, 0x1e, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x70, 0x61, 0x70, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x50, 0x61, 0x70, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x70, 0x61, 0x70, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x50, 0x61, 0x70, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x14, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x0e, 0x12, 0x09, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x61, 0x70, 0x65, 0x72, 0x3a, 0x01,
	0x2a, 0x42, 0x4a, 0x0a, 0x0c, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x61, 0x70, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x50, 0x01, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6d, 0x69, 0x74, 0x74, 0x61, 0x63, 0x79, 0x2f, 0x68, 0x69, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x61, 0x70, 0x65, 0x72, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x70, 0x61, 0x70, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_paper_v1_paper_proto_rawDescOnce sync.Once
	file_api_paper_v1_paper_proto_rawDescData = file_api_paper_v1_paper_proto_rawDesc
)

func file_api_paper_v1_paper_proto_rawDescGZIP() []byte {
	file_api_paper_v1_paper_proto_rawDescOnce.Do(func() {
		file_api_paper_v1_paper_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_paper_v1_paper_proto_rawDescData)
	})
	return file_api_paper_v1_paper_proto_rawDescData
}

var file_api_paper_v1_paper_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_paper_v1_paper_proto_goTypes = []interface{}{
	(*CreatePaperRequest)(nil),  // 0: api.paper.v1.CreatePaperRequest
	(*CreatePaperReply)(nil),    // 1: api.paper.v1.CreatePaperReply
	(*UpdatePaperRequest)(nil),  // 2: api.paper.v1.UpdatePaperRequest
	(*UpdatePaperReply)(nil),    // 3: api.paper.v1.UpdatePaperReply
	(*DeletePaperRequest)(nil),  // 4: api.paper.v1.DeletePaperRequest
	(*DeletePaperReply)(nil),    // 5: api.paper.v1.DeletePaperReply
	(*GetPaperRequest)(nil),     // 6: api.paper.v1.GetPaperRequest
	(*GetPaperReply)(nil),       // 7: api.paper.v1.GetPaperReply
	(*GetPaperCodeRequest)(nil), // 8: api.paper.v1.GetPaperCodeRequest
	(*GetPaperCodeReply)(nil),   // 9: api.paper.v1.GetPaperCodeReply
	(*ListPaperRequest)(nil),    // 10: api.paper.v1.ListPaperRequest
	(*ListPaperReply)(nil),      // 11: api.paper.v1.ListPaperReply
	(*PaperStruct)(nil),         // 12: api.paper.v1.PaperStruct
}
var file_api_paper_v1_paper_proto_depIdxs = []int32{
	12, // 0: api.paper.v1.GetPaperReply.paper:type_name -> api.paper.v1.PaperStruct
	12, // 1: api.paper.v1.ListPaperReply.papers:type_name -> api.paper.v1.PaperStruct
	0,  // 2: api.paper.v1.Paper.CreatePaper:input_type -> api.paper.v1.CreatePaperRequest
	2,  // 3: api.paper.v1.Paper.UpdatePaper:input_type -> api.paper.v1.UpdatePaperRequest
	4,  // 4: api.paper.v1.Paper.DeletePaper:input_type -> api.paper.v1.DeletePaperRequest
	6,  // 5: api.paper.v1.Paper.GetPaper:input_type -> api.paper.v1.GetPaperRequest
	8,  // 6: api.paper.v1.Paper.GetPaperCode:input_type -> api.paper.v1.GetPaperCodeRequest
	10, // 7: api.paper.v1.Paper.ListPaper:input_type -> api.paper.v1.ListPaperRequest
	1,  // 8: api.paper.v1.Paper.CreatePaper:output_type -> api.paper.v1.CreatePaperReply
	3,  // 9: api.paper.v1.Paper.UpdatePaper:output_type -> api.paper.v1.UpdatePaperReply
	5,  // 10: api.paper.v1.Paper.DeletePaper:output_type -> api.paper.v1.DeletePaperReply
	7,  // 11: api.paper.v1.Paper.GetPaper:output_type -> api.paper.v1.GetPaperReply
	9,  // 12: api.paper.v1.Paper.GetPaperCode:output_type -> api.paper.v1.GetPaperCodeReply
	11, // 13: api.paper.v1.Paper.ListPaper:output_type -> api.paper.v1.ListPaperReply
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_paper_v1_paper_proto_init() }
func file_api_paper_v1_paper_proto_init() {
	if File_api_paper_v1_paper_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_paper_v1_paper_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePaperRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_paper_v1_paper_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePaperReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_paper_v1_paper_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePaperRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_paper_v1_paper_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePaperReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_paper_v1_paper_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePaperRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_paper_v1_paper_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePaperReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_paper_v1_paper_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPaperRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_paper_v1_paper_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPaperReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_paper_v1_paper_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPaperCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_paper_v1_paper_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPaperCodeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_paper_v1_paper_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPaperRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_paper_v1_paper_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPaperReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_paper_v1_paper_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaperStruct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_paper_v1_paper_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_paper_v1_paper_proto_goTypes,
		DependencyIndexes: file_api_paper_v1_paper_proto_depIdxs,
		MessageInfos:      file_api_paper_v1_paper_proto_msgTypes,
	}.Build()
	File_api_paper_v1_paper_proto = out.File
	file_api_paper_v1_paper_proto_rawDesc = nil
	file_api_paper_v1_paper_proto_goTypes = nil
	file_api_paper_v1_paper_proto_depIdxs = nil
}
